version: '3.8'

services:
  # Frontend React (desarrollo con hot reload)
  frontend:
    build:
      context: ./SaludaFront
      dockerfile: Dockerfile.dev
    container_name: saludafront_dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./SaludaFront:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - saludanetwork
    restart: unless-stopped

  # Backend Laravel (desarrollo)
  backend:
    build:
      context: ./SaludaBack
      dockerfile: Dockerfile.dev
    container_name: saludaback_dev
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SECOND_HOST=${DB_SECOND_HOST}
      - DB_SECOND_PORT=${DB_SECOND_PORT}
      - DB_SECOND_DATABASE=${DB_SECOND_DATABASE}
      - DB_SECOND_USERNAME=${DB_SECOND_USERNAME}
      - DB_SECOND_PASSWORD=${DB_SECOND_PASSWORD}
    volumes:
      - ./SaludaBack:/var/www/html
      - ./SaludaBack/storage:/var/www/html/storage
      - ./SaludaBack/bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - saludanetwork
    restart: unless-stopped

networks:
  saludanetwork:
    driver: bridge 